# omniASR Streaming Server - Podman Compose (GPU)
#
# Usage:
#   podman-compose -f podman-compose.yml up -d
#
# Or run directly with podman:
#   podman run --rm -it --device nvidia.com/gpu=all \
#     -p 8080:8080 localhost/adeo-omniasr-server:latest

services:
  omniASR-gpu:
    image: localhost/adeo-omniasr-server:latest
    container_name: omniasr-gpu
    # IMPORTANT: Do not load .env file - all config is baked into the Docker image
    # The Dockerfile already has all ENV vars set. Local .env is for dev server only.
    env_file: []
    ports:
      - "8080:8080"
    # Podman GPU passthrough using CDI (Container Device Interface)
    devices:
      - nvidia.com/gpu=all
    security_opt:
      - label=disable
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
